### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by andy144** [sinedie/SRT-DeepL-Translator#10]
Hi, I'm a newbie.
Can you please give an example on how to use it?
I installed it ok, but don't understand how/where to put file name to translate,
and the one to translate to.
Thanx

**Comment by andy144** [comment]
I mean, this is how I do,
python main.py -i en -o fr path /home/chi/SRT-DeepL-Translator-master/q.srt

and then I see these errors:

Traceback (most recent call last):
  File "/home/chi/SRT-DeepL-Translator-master/main.py", line 87, in <module>
    translator = deepl.translator()
  File "/home/chi/SRT-DeepL-Translator-master/deepl.py", line 19, in __init__
    self.browser = webdriver.Firefox(executable_path=geckodriver_path)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by sinedie** [comment]
At this moment it is on early development and was a little on pause. Im glad people start using it.

It should be like this:
`python main.py -i en -o fr /home/chi/SRT-DeepL-Translator-master`

Without `path` word and check that the path is to the folder where subtitles are. It will take every srt on the folder and save the traslation in the same folder but with a different name:

q.str => q_fr.srt

Hope it is clear enough, glad to help. Probably it will fail, im think on rewriting it. Maybe today, idk, keep you updated.

Probably doing a graphical user interface could be more user friendly. But that is another issue. Gonna think about it.

**Comment by andy144** [comment]
> At this moment it is on early development and was a little on pause. Im glad people start using it.
> 
> It should be like this:
> `python main.py -i en -o fr /home/chi/SRT-DeepL-Translator-master`
> 
> Without `path` word and check that the path is to the folder where subtitles are. It will take every srt on the folder and save the traslation in the same folder but with a different name:
> 
> q.str => q_fr.srt
> 
> Hope it is clear enough, glad to help. Probably it will fail, im think on rewriting it. Maybe today, idk, keep you updated.
> 
> Probably doing a graphical user interface could be more user friendly. But that is another issue. Gonna think about it.

Thanx, I did that but still throws the same errors.
Could also be an installation problem?
I have installed: python-urllib3 1.26.4-1
                          python-selenium 3.141.0-3
                          geckodriver 0.26.0-1

**Comment by sinedie** [comment]
I dont think so. Maybe a problem with geckodriver version. But i'll recommend you to wait for the next release. It wont be long.

In the mean time i pushed a new version refactored. 0.8.2. Havent review it yet so bugs expected, but it should be fixed it think. This new version install the last version of geckodriver so no need to worry about it.

Also, It use easygui for better user experience, you could check it out using:  `python main.py -g`

This is still a work in progress but  check in one week or two for version 1.0 and soon will be on pypi for installation via `pip install srt_deepl.`

**Comment by sinedie** [comment]
@andy144 Check out the readme again. Now you can use this from your own scripts:

install it like:

```
pip install srt-deepl
```

use like from python:

```
from srt-test import translate
translate(...)
```

Or by command line: (still need installation by pip)

Easy way
```
python -m srt_deepl -g
```

See the help for advance use
```
python -m srt_deepl -h
```

I think it is clear enough, gonna close this issue. Feel free to open it again if something isn't clear.

Regrads, EAR

**Comment by andy144** [comment]
Ok, still not working.
This is what I did.

Installation:
[chi@PC SRT-DeepL-Translator-master]$ pip install srt-deepl
Defaulting to user installation because normal site-packages is not writeable
Collecting srt-deepl
  Downloading srt_deepl-0.8.5-py3-none-any.whl (7.3 kB)
Requirement already satisfied: geckodriver-autoinstaller==0.1.0 in /home/chi/.local/lib/python3.9/site-packages (from srt-deepl) (0.1.0)
Requirement already satisfied: easygui==0.98.2 in /home/chi/.local/lib/python3.9/site-packages (from srt-deepl) (0.98.2)
Requirement already satisfied: urllib3==1.26.5 in /home/chi/.local/lib/python3.9/site-packages (from srt-deepl) (1.26.5)
Requirement already satisfied: selenium==3.141.0 in /usr/lib/python3.9/site-packages (from srt-deepl) (3.141.0)
Requirement already satisfied: pyperclip==1.8.2 in /home/chi/.local/lib/python3.9/site-packages (from srt-deepl) (1.8.2)
Requirement already satisfied: srt==3.4.1 in /home/chi/.local/lib/python3.9/site-packages (from srt-deepl) (3.4.1)
Requirement already satisfied: urllib3==1.26.5 in /home/chi/.local/lib/python3.9/site-packages (from srt-deepl) (1.26.5)
Installing collected packages: srt-deepl
Successfully installed srt-deepl-0.8.5

so I guess all ok by now.
But then I started it with:    python -m srt_deepl -g
Graphical works, I chose srt folder, checked languages, and then:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chi/SRT-DeepL-Translator-master/srt_deepl/__main__.py", line 104, in <module>
    os.environ["MOZ_HEADLESS"] = "1"
NameError: name 'os' is not defined

any idea? :D

**Comment by sinedie** [comment]
Oh shit, my bad, lol. What a stupid mistake, forgot to import `os`. It is fixed by now. (still need to review, ty for finding this, you rock!)

Now, you need to update to the new version. You actually have 0.8.5, and just pushed 0.8.6 with this fix. The fastest way is to uninstalling and installing again.

```
pip uninstall srt-deepl
pip install srt-deepl
```

**Comment by andy144** [comment]
Still not working. This time, after 'python -m srt_deepl -g'
it takes a long pause (about 30s) and these errors pops up:

Successfully installed srt-deepl-0.8.6
[chi@PC SRT-DeepL-Translator-master]$ python -m srt_deepl -g
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chi/SRT-DeepL-Translator-master/srt_deepl/__main__.py", line 107, in <module>
    translate(
  File "/home/chi/SRT-DeepL-Translator-master/srt_deepl/main.py", line 94, in translate
    subs = translator.translate(
  File "/home/chi/SRT-DeepL-Translator-master/srt_deepl/deepl.py", line 94, in translate
    raise Exception(
Exception: Timeout for traslating portion.

                    Make sure your SRT file does not contain the characters '[...]'




I checked the srt, it doesn't have any ... characters.
Tried with other srt also and same message appears.

**Comment by sinedie** [comment]
Yeah it takes a lot of time to translate. Maybe cause your network connection. It divides the srt into portions to translate each one of them in the deepl webpage... only 5000 character at time, so it will take a while.

The character is `[...]` including `[` and `]` cause it is needed to check if it is already translated.

This issue must be of your internet connection. It timeout after 60 sec if no traslation is done. I make it this way to not wait a long time, but maybe could be good to make it bigger. Try with a short srt and tell me if the issue persist.

**Comment by sinedie** [comment]
If it persist. Try updating again (yeah i know... told you, lots of bugs) to 0.8.7 and use `python -m srt_deepl -g -s` to show the browser and see what is happening.

**Comment by andy144** [comment]
well, I did as you said with a 7 rows srt and it was exactly the same.
browser is not opening. I opened it myself, but nothing happened.
I don't usually use firefox, so I made it default. but still didn't work.
internet is working fine, up to 25-30 MB/s download.

**Comment by sinedie** [comment]
Ok... that's weird. Im gonna ask you a favor... update again. Check that it is version 0.8.9 and use it again and tell me if it works.

**Comment by andy144** [comment]
installed 0.8.9. same :)
what is the server that has to be accessed?
Maybe it blocks some regions?
deepl site works fine.

**Comment by andy144** [comment]
wait. it works!
my fault. apologies.
I was starting the terminal from the parent folder of srt_deepl,
instead of srt_deepl.
sorry, sorry, sorry! :)

**Comment by sinedie** [comment]
Oh okay, was writing a response but well. Im really glad about it. (You dont need the source code for run it, just with installing with pip is enough)

Enjoy and dont hesitate on ask :DD

**Comment by andy144** [comment]
thanks a lot!
I'll test it and come back for other improvements,
if necessary.

**Comment by andy144** [comment]
One more little problem.
Right now I have to translate many long subtitles (about 1600 lines each).
I noticed that deepl doesn't accept that and suspends your access for a while.
I then split them in 2 and it worked like a charm, for about 5-6 srts, after which
they suspended my access again.
So, question: can you change browser to Tor? :)
I translated some docx files like that, you know,
having other ip on every Tor instance.
Or maybe tell me how to do it, if it's not very complicated.

**Comment by andy144** [comment]
I'm on archlinux, and it's called 'tor_browser'

**Comment by sinedie** [comment]
Oh... yeah that didnt had happened to me (maybe cause i dont use it that often...) I understand that... and have some ideas about it by now. But im gonna ask you to open a new issue. That way if someone else have the same issue can find it. I'll anwser there. Ty
